### ISSUE TITLE
Turn off pglogical

### ISSUE THREAD

**Issue by reginafcompton** [datamade/scrapers-us-municipal#1]
Recently, we ran out of disk space on the scraper server, [due to the size of pg_xlog](http://blog.endpoint.com/2014/09/pgxlog-disk-space-problem-on-postgres.html). 

We need to turn off pglogical: https://github.com/2ndQuadrant/pglogical

**Comment by reginafcompton** [comment]
Note: _What did we do (for short term resolution)?_ As the postgres user, we cd'd to `~/9.5/main/pg_xlog`, and then tidied the archive: https://www.postgresql.org/docs/9.2/static/pgarchivecleanup.html

**Comment by fgregg** [comment]
I turned off pglogical by 

`drop extension pglogical cascade`
