### ISSUE TITLE
Handle new identifiers 

### ISSUE THREAD

**Issue by reginafcompton** [datamade/scrapers-us-municipal#12]
We plan to open a branch on Pupa that removes use of [`fix_bill_id`](https://github.com/opencivicdata/pupa/blob/master/pupa/utils/generic.py#L34), a function that cleans identifiers and resultantly removes leading 0's: https://github.com/opencivicdata/pupa/issues/163. Upstream, the change will help resolve [this NYC Councilmatic issue](https://github.com/datamade/nyc-council-councilmatic/issues/100) in particular.

This change will alter identifiers in our OCD database. We need to take a couple steps to preserve our data:

**OCD API database**
- [x] Write a migration that prevents the creation of duplicate entries in the OCD API (since new identifiers result in new ocd_ids). The migration could be a formal migration with [RUNsql](https://docs.djangoproject.com/en/2.0/ref/migration-operations/#runsql), (possibly residing in the [OCD API django app](https://github.com/datamade/api.opencivicdata.org) or a manual migration. The migration has to account for the differences in location, so we'd need something like:

```
update bills set identifier = [some operation to pad a leading zero] 
where from_organization='metro..'

update bills set identifier = [some operation to pad a leading zero] 
where from_organization='nyc...'

update bills set identifier = [some operation to pad a leading zero]
where from_organization='chicago...'
```

**Councilmatic side**
- [x] Write a migration for the Councilmatic databases that adjusts the identifiers (i.e., adds leading 0's where expected - similar to above). We also need a migration to account for [related bills](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L1399) and [slugs](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L959)  – the slug should be consistent with the new identifiers, but this could cause some problems......exercise caution here.
- [x] Set up redirects, i.e., building upon our [current redirects for bills](https://github.com/datamade/nyc-council-councilmatic/blob/master/nyc/views.py#L26).
- [ ] Rebuild solr indices (so the search functionality knows about our new identifiers).

**Comment by fgregg** [comment]
We also need a "migration" for the councilmatic databases.

**Comment by reginafcompton** [comment]
@fgregg - got it. Anything else?

**Comment by fgregg** [comment]
We'll need to turn off scrapers and import data while we are doing this migration and turn them back on afterwards. Probably worth making a little checklist.

**Comment by reginafcompton** [comment]
A fix for mangling bill identifiers came through about 4 days ago! We can proceed with this issue.

**Comment by hancush** [comment]
First question: Are leading zeroes standard across jurisdictions? Or, at least, within a jurisdiction?

One we have that answered, I will handle changes to the OCD API database & @reginafcompton will handle changes to Councilmatic (either core or each of the jurisdictions; if the latter, I can def pitch in).

**Comment by hancush** [comment]
Allow me to clarify that @reginafcompton is going to look into the leading zero question, this afternoon.

**Comment by reginafcompton** [comment]
[Relevant pupa fix for reference](https://github.com/opencivicdata/pupa/commit/a770022f0d1ceacf6c1183c7c0259f02c5c6ef0d)

**Comment by reginafcompton** [comment]
_What I've learned on the Councilmatic side_

**LA Metro**
LA Metro has consistently used the year at the beginning of their identifiers (e.g., '2017-0871', '2015-1434'). I confirmed this by searching for bills that did not have a length of 9. The query returned only two bills (2016-228 and 2016-217): looking at their source in Legistar, I can conclude that the `fix_bill_id` function did not mangle either.

```
# Find bills that may have been shortened (returns 2 results)
select identifier from councilmatic_core_bill where length(identifier) != 9;
# Find bills that do not begin with a year stamp (returns 0 results)
select identifier from councilmatic_core_bill where identifier not like '201%';
```
At the time of testing, Metro had 1364 bills in their database. 

**NYC Councilmatic**

**Comment by reginafcompton** [comment]
@hancush - I left some initial exploratory thoughts on the mangled bill IDs. It seems that NYC will require a fun-and-fancy migration, but not Metro and Chicago.

**Comment by hancush** [comment]
I guess that's why they call NYC "The Fun & Fancy City"!

**Comment by reginafcompton** [comment]
**To do**

Chicago may not be as consistent as it seems, particularly with regard to spacing. For example, it's possible that a space may or may not occur between the intro letter and the subsequent digits. _Check on this!_

**Comment by reginafcompton** [comment]
**More notes on NYC**

I am trying to get an understanding of what *is* consistent among identifiers in Legistar. I ran a few queries against the API - basically, looking for bills that would have been affected by `fix_bill_id`. I used the `startswith` argument and looked at the MatterFile:

https://webapi.legistar.com/v1/nyc/matters?$filter=startswith(MatterFile,%20%27LU%200%27)&token=...

_Params that return results_
'LU 0'
'Int 0'
'M 0'
'Res 0'
'SLR 0'
(N.B. these params only return results when a space is present.)

It appears that NYC bill identifiers should match this RegEx:
`r'^\w{1,3}\s\d{4}-\d{4}$'` or (without a space) `r'^\w{1,3}\s\d{4}-\d{4}$'

If not, then they were mangled by `fix_bill_id` in a couple ways:
(1) leading zeroes were removed.
(2) a space was added between the letters that indicate bill type and the unique number. For example,[this bill](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=1690639&GUID=F03D97D3-D1A0-463A-94A0-B9603020849E&Options=ID|Text|&Search=) gets [the identifier shown here](https://ocd.datamade.us/ocd-bill/21b40229-7ef7-46e2-a750-14fd26189330/)

Obviously, I need to spend more time thinking about the above.

It would be great if the Legistar API could accept regex to see if there are exceptions, but that does not seem to be possible provided [this documentation](http://www.odata.org/documentation/odata-version-3-0/url-conventions/).

**Comment by reginafcompton** [comment]
*Next Steps*

(1) Translate the Councilmatic [migration logic](https://github.com/datamade/django-councilmatic/pull/190) to OpenCivicData.
(2) Run the migration locally on the `opencivicdata` database. 
(3) Run `pupa update` and look for edge cases. Make any adjustments to the migration, as needed. 

Then, do the same with Chicago.

**Comment by reginafcompton** [comment]
Are all the migrations and redirects in place? Good. Follow these exact, ordered steps:

*Preparation: Turn off cron*
(1) Turn off [cronjobs for the scrapers](https://github.com/datamade/scrapers-us-municipal/blob/master/scripts/scrapers-us-municipal-crontask).
(2) Turn off [cronjobs for NYC](https://github.com/datamade/nyc-council-councilmatic/tree/master/scripts) - both staging and production
(3) Turn off [cronjobs for Chicago](https://github.com/datamade/chi-councilmatic/tree/master/scripts) - both staging and production

*OCD API migrations*
Merge the [`unmangle-identifiers` branch'](https://github.com/datamade/api.opencivicdata.org/pull/30), and cut a new release (i.e., deploy to the production server). The `after_install` script runs migrations, but spot check that the identifiers changed as expected. 

*Upgrade django-councilmatic and run migrations*
(1) Merge the [identifier-migration](https://github.com/datamade/django-councilmatic/pull/190) branch into master, and cut a new release of django-councilmatic.
(2) Pin [NYC to this version](https://github.com/datamade/nyc-council-councilmatic/pull/136).
(3) Pin Chicago to this version - remember to update [the settings with a jurisdiction list](https://github.com/datamade/chi-councilmatic/blob/master/councilmatic/settings_jurisdiction.py#L9)!
(4) Deploy NYC and Chicago to staging and production - the migrations will run, but check that bills were modified as expected.

**Comment by reginafcompton** [comment]
@fgregg - let's schedule a time to put this into action. Monday morning would be best (I think).

**Comment by fgregg** [comment]
Looking good! Can you make out the checklist. After that inform the clients @reginafcompton

**Comment by reginafcompton** [comment]
Done! The Unmangler can rest.
