### ISSUE TITLE
Create deployment branch and enable push deploys

### ISSUE THREAD

**Issue by reginafcompton** [datamade/scrapers-us-municipal#2]
CodeDeploy to the rescue! 

* enable push deploys
* put configuration files in version control
* put cronjobs in version control and use FLOCK

**DEADLINE: JULY 7**

**Comment by reginafcompton** [comment]
@jeancochrane: I plan to spend Wednesday working on this.

**Comment by jeancochrane** [comment]
OK! I'll plan to be available to help out. Let's aim to get the new logging system up and running, too.

**Comment by reginafcompton** [comment]
scrapers-us-municipal can now be deployed via AWS Codedeploy with tagged commits (i.e., version numbers). 

Cronjobs are also stored under version control. Here's documentation of how it works: https://github.com/datamade/deploy-a-site/blob/master/Adding-crontasks.md

@fgregg if this looks good, we can go ahead and replace the current scraper repo on the ocd server with the one triggered by Codedeploy (currently, called "crapers-us-municipal-codedeploy").

**Comment by fgregg** [comment]
Please add @hancush, @evz and @fgregg to blackbox.

**Comment by fgregg** [comment]
lgtm. go for it.

**Comment by reginafcompton** [comment]
It's implemented. I marked the old repo as "scrapers-us-municipal-old," in case we need it as a reference point in the future.
